name:                polyglot
version:             0.1.1.0
github:              "albertprz/polyglot"
license:             BSD3
author:              "Alberto Perez Lopez"
maintainer:          "albertoperez1994@gmail.com"
copyright:           "2022 Alberto Perez Lopez"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Haskell to Purescript & Scala 3 transpiler
category:            Compiler

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/albertprz/polyglot#readme>

dependencies:
- bookhound
- optparse-applicative
- filepath
- directory
- directory-tree
- fsnotify
- parallel
- casing

- base >= 4 && < 5
- classy-prelude
- mtl
- text
- bytestring
- containers
- extra

language: GHC2021

default-extensions:
# Prelude
- NoImplicitPrelude

# Evaluation
- StrictData

# Syntax
- LambdaCase
- MultiWayIf
- BlockArguments
- PostfixOperators

# Types
- LiberalTypeSynonyms
- FunctionalDependencies

# Records
- DuplicateRecordFields
- NoFieldSelectors
- RecordWildCards
- OverloadedRecordDot

# Convenience
- ApplicativeDo
- OverloadedStrings
- ViewPatterns

# Type Level Programming
- GADTs
- TypeFamilies
- TypeFamilyDependencies
- DataKinds

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints


library:
  source-dirs: src

executables:
  polyglot:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - polyglot
