packages:
- .
resolver:
  compiler: ghc-9.2.1
extra-deps:
- bookhound-0.1.9.0
- filepath-1.4.2.2
- optparse-applicative-0.17.0.0

- extra-1.7.10
- utility-ht-0.0.16

- directory-1.3.7.0
- process-1.6.14.0
- transformers-compat-0.7.1
- clock-0.8.3
- ansi-wl-pprint-0.6.9
- ansi-terminal-0.11.3
- colour-2.3.6
